# Generated by Django 5.0 on 2024-01-22 21:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_playlist_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlist",
            old_name="thumbnail",
            new_name="picture",
        ),
    ]
